import java.io.FileNotFoundException;
import java.io.IOException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
//Test and verifying data for Command Guard Services Timesheet
public class TimeSheetTest {
	static WebDriver driver;
	@BeforeTest
	public static void configureDriver() throws FileNotFoundException, IOException, InterruptedException {
		System.setProperty("webdriver.edge.driver", "src/MicrosoftWebDriver.exe");
		driver = new EdgeDriver();
		driver.get("localhost/security-guard-timesheet.html");
	}
	@Test
	public void test() {
		new TimeSheet(driver);	
		TimeSheet.enterWorkSite().sendKeys(Data.myList[0]);
		TimeSheet.enterFirstSatDate().sendKeys(Data.myList[1]);
		TimeSheet.enterFirstSatTimeOnDuty().sendKeys(Data.myList[2]);
		TimeSheet.enterFirstSatEmployeeName().sendKeys(Data.myList[3]);
		TimeSheet.enterFirstSatBreakStart().sendKeys(Data.myList[4]);
		TimeSheet.enterFirstSatBreakEnd().sendKeys(Data.myList[5]);
		TimeSheet.enterFirstSatTimeOff().sendKeys(Data.myList[6]);
		TimeSheet.enterFirstSatTotalHour().sendKeys(Data.myList[7]);
		TimeSheet.enterFirstSatEmployeeSignature().sendKeys(Data.myList[8]);
		TimeSheet.enterFirstSatClientSignature().sendKeys(Data.myList[9]);
		TimeSheet.enterSecondSatDate().sendKeys(Data.myList[10]);
		TimeSheet.enterSecondSatTimeOnDuty().sendKeys(Data.myList[11]);
		TimeSheet.enterSecondSatEmployeeName().sendKeys(Data.myList[12]);
		TimeSheet.enterSecondSatBreakStart().sendKeys(Data.myList[13]);
		TimeSheet.enterSecondSatBreakEnd().sendKeys(Data.myList[14]);
		TimeSheet.enterSecondSatTimeOff().sendKeys(Data.myList[15]);
		TimeSheet.enterSecondSatTotalHour().sendKeys(Data.myList[16]);
		TimeSheet.enterSecondSatEmployeeSignature().sendKeys(Data.myList[17]);
		TimeSheet.enterSecondSatClientSignature().sendKeys(Data.myList[18]);
		TimeSheet.enterFirstSunDate().sendKeys(Data.myList[19]);
		TimeSheet.enterFirstSunTimeOnDuty().sendKeys(Data.myList[20]);
		TimeSheet.enterFirstSunEmployeeName().sendKeys(Data.myList[21]);
		TimeSheet.enterFirstSunBreakStart().sendKeys(Data.myList[22]);
		TimeSheet.enterFirstSunBreakEnd().sendKeys(Data.myList[23]);
		TimeSheet.enterFirstSunTimeOff().sendKeys(Data.myList[24]);
		TimeSheet.enterFirstSunTotalHour().sendKeys(Data.myList[25]);
		TimeSheet.enterFirstSunEmployeeSignature().sendKeys(Data.myList[26]);
		TimeSheet.enterFirstSunClientSignature().sendKeys(Data.myList[27]);
		TimeSheet.enterSecondSunDate().sendKeys(Data.myList[28]);
		TimeSheet.enterSecondSunTimeOnDuty().sendKeys(Data.myList[29]);
		TimeSheet.enterSecondSunEmployeeName().sendKeys(Data.myList[30]);
		TimeSheet.enterSecondSunBreakStart().sendKeys(Data.myList[31]);
		TimeSheet.enterSecondSunBreakEnd().sendKeys(Data.myList[32]);
		TimeSheet.enterSecondSunTimeOff().sendKeys(Data.myList[33]);
		TimeSheet.enterSecondSunTotalHour().sendKeys(Data.myList[34]);
		TimeSheet.enterSecondSunEmployeeSignature().sendKeys(Data.myList[35]);
		TimeSheet.enterSecondSunClientSignature().sendKeys(Data.myList[36]);
		TimeSheet.enterFirstMonDate().sendKeys(Data.myList[37]);
		TimeSheet.enterFirstMonTimeOnDuty().sendKeys(Data.myList[38]);
		TimeSheet.enterFirstMonEmployeeName().sendKeys(Data.myList[39]);
		TimeSheet.enterFirstMonBreakStart().sendKeys(Data.myList[40]);
		TimeSheet.enterFirstMonBreakEnd().sendKeys(Data.myList[41]);
		TimeSheet.enterFirstMonTimeOff().sendKeys(Data.myList[42]);
		TimeSheet.enterFirstMonTotalHour().sendKeys(Data.myList[43]);
		TimeSheet.enterFirstMonEmployeeSignature().sendKeys(Data.myList[44]);
		TimeSheet.enterFirstMonClientSignature().sendKeys(Data.myList[45]);
		TimeSheet.enterSecondMonDate().sendKeys(Data.myList[46]);
		TimeSheet.enterSecondMonTimeOnDuty().sendKeys(Data.myList[47]);
		TimeSheet.enterSecondMonEmployeeName().sendKeys(Data.myList[48]);
		TimeSheet.enterSecondMonBreakStart().sendKeys(Data.myList[49]);
		TimeSheet.enterSecondMonBreakEnd().sendKeys(Data.myList[50]);
		TimeSheet.enterSecondMonTimeOff().sendKeys(Data.myList[51]);
		TimeSheet.enterSecondMonTotalHour().sendKeys(Data.myList[52]);
		TimeSheet.enterSecondMonEmployeeSignature().sendKeys(Data.myList[53]);
		TimeSheet.enterSecondMonClientSignature().sendKeys(Data.myList[54]);
		TimeSheet.enterFirstTueDate().sendKeys(Data.myList[55]);
		TimeSheet.enterFirstTueTimeOnDuty().sendKeys(Data.myList[56]);
		TimeSheet.enterFirstTueEmployeeName().sendKeys(Data.myList[57]);
		TimeSheet.enterFirstTueBreakStart().sendKeys(Data.myList[58]);
		TimeSheet.enterFirstTueBreakEnd().sendKeys(Data.myList[59]);
		TimeSheet.enterFirstTueTimeOff().sendKeys(Data.myList[60]);
		TimeSheet.enterFirstTueTotalHour().sendKeys(Data.myList[61]);
		TimeSheet.enterFirstTueEmployeeSignature().sendKeys(Data.myList[62]);
		TimeSheet.enterFirstTueClientSignature().sendKeys(Data.myList[63]);
		TimeSheet.enterSecondTueDate().sendKeys(Data.myList[64]);
		TimeSheet.enterSecondTueTimeOnDuty().sendKeys(Data.myList[65]);
		TimeSheet.enterSecondTueEmployeeName().sendKeys(Data.myList[66]);
		TimeSheet.enterSecondTueBreakStart().sendKeys(Data.myList[67]);
		TimeSheet.enterSecondTueBreakEnd().sendKeys(Data.myList[68]);
		TimeSheet.enterSecondTueTimeOff().sendKeys(Data.myList[69]);
		TimeSheet.enterSecondTueTotalHour().sendKeys(Data.myList[70]);
		TimeSheet.enterSecondTueEmployeeSignature().sendKeys(Data.myList[71]);
		TimeSheet.enterSecondTueClientSignature().sendKeys(Data.myList[72]);
		TimeSheet.enterFirstWedDate().sendKeys(Data.myList[73]);
		TimeSheet.enterFirstWedTimeOnDuty().sendKeys(Data.myList[74]);
		TimeSheet.enterFirstWedEmployeeName().sendKeys(Data.myList[75]);
		TimeSheet.enterFirstWedBreakStart().sendKeys(Data.myList[76]);
		TimeSheet.enterFirstWedBreakEnd().sendKeys(Data.myList[77]);
		TimeSheet.enterFirstWedTimeOff().sendKeys(Data.myList[78]);
		TimeSheet.enterFirstWedTotalHour().sendKeys(Data.myList[79]);
		TimeSheet.enterFirstWedEmployeeSignature().sendKeys(Data.myList[80]);
		TimeSheet.enterFirstWedClientSignature().sendKeys(Data.myList[81]);
		TimeSheet.enterSecondWedDate().sendKeys(Data.myList[82]);
		TimeSheet.enterSecondWedTimeOnDuty().sendKeys(Data.myList[83]);
		TimeSheet.enterSecondWedEmployeeName().sendKeys(Data.myList[84]);
		TimeSheet.enterSecondWedBreakStart().sendKeys(Data.myList[85]);
		TimeSheet.enterSecondWedBreakEnd().sendKeys(Data.myList[86]);
		TimeSheet.enterSecondWedTimeOff().sendKeys(Data.myList[87]);
		TimeSheet.enterSecondWedTotalHour().sendKeys(Data.myList[88]);
		TimeSheet.enterSecondWedEmployeeSignature().sendKeys(Data.myList[89]);
		TimeSheet.enterSecondWedClientSignature().sendKeys(Data.myList[90]);
		TimeSheet.enterFirstThurDate().sendKeys(Data.myList[91]);
		TimeSheet.enterFirstThurTimeOnDuty().sendKeys(Data.myList[92]);
		TimeSheet.enterFirstThurEmployeeName().sendKeys(Data.myList[93]);
		TimeSheet.enterFirstThurBreakStart().sendKeys(Data.myList[94]);
		TimeSheet.enterFirstThurBreakEnd().sendKeys(Data.myList[95]);
		TimeSheet.enterFirstThurTimeOff().sendKeys(Data.myList[96]);
		TimeSheet.enterFirstThurTotalHour().sendKeys(Data.myList[97]);
		TimeSheet.enterFirstThurEmployeeSignature().sendKeys(Data.myList[98]);
		TimeSheet.enterFirstThurClientSignature().sendKeys(Data.myList[99]);
		TimeSheet.enterSecondThurDate().sendKeys(Data.myList[100]);
		TimeSheet.enterSecondThurTimeOnDuty().sendKeys(Data.myList[101]);
		TimeSheet.enterSecondThurEmployeeName().sendKeys(Data.myList[102]);
		TimeSheet.enterSecondThurBreakStart().sendKeys(Data.myList[103]);
		TimeSheet.enterSecondThurBreakEnd().sendKeys(Data.myList[104]);
		TimeSheet.enterSecondThurTimeOff().sendKeys(Data.myList[105]);
		TimeSheet.enterSecondThurTotalHour().sendKeys(Data.myList[106]);
		TimeSheet.enterSecondThurEmployeeSignature().sendKeys(Data.myList[107]);
		TimeSheet.enterSecondThurClientSignature().sendKeys(Data.myList[108]);
		TimeSheet.enterFirstFriDate().sendKeys(Data.myList[109]);
		TimeSheet.enterFirstFriTimeOnDuty().sendKeys(Data.myList[110]);
		TimeSheet.enterFirstFriEmployeeName().sendKeys(Data.myList[111]);
		TimeSheet.enterFirstFriBreakStart().sendKeys(Data.myList[112]);
		TimeSheet.enterFirstFriBreakEnd().sendKeys(Data.myList[113]);
		TimeSheet.enterFirstFriTimeOff().sendKeys(Data.myList[114]);
		TimeSheet.enterFirstFriTotalHour().sendKeys(Data.myList[115]);
		TimeSheet.enterFirstFriEmployeeSignature().sendKeys(Data.myList[116]);
		TimeSheet.enterFirstFriClientSignature().sendKeys(Data.myList[117]);
		TimeSheet.enterSecondFriDate().sendKeys(Data.myList[118]);
		TimeSheet.enterSecondFriTimeOnDuty().sendKeys(Data.myList[119]);
		TimeSheet.enterSecondFriEmployeeName().sendKeys(Data.myList[120]);
		TimeSheet.enterSecondFriBreakStart().sendKeys(Data.myList[121]);
		TimeSheet.enterSecondFriBreakEnd().sendKeys(Data.myList[122]);
		TimeSheet.enterSecondFriTimeOff().sendKeys(Data.myList[123]);
		TimeSheet.enterSecondFriTotalHour().sendKeys(Data.myList[124]);
		TimeSheet.enterSecondFriEmployeeSignature().sendKeys(Data.myList[125]);
		TimeSheet.enterSecondFriClientSignature().sendKeys(Data.myList[126]);
		TimeSheet.enterFirstEmployeeInitial().sendKeys(Data.myList[127]);
		TimeSheet.enterSecondEmployeeInitial().sendKeys(Data.myList[128]);
		TimeSheet.enterEmployeeSig().sendKeys(Data.myList[129]);
		}
	@AfterTest
	public void endTest() throws FileNotFoundException, IOException {
		OpenReport.openExcel();
		driver.quit();
	}

}
